### ISSUE TITLE
Category legend

### ISSUE THREAD

**Issue by FunWithWP** [afragen/the-events-calendar-category-colors#100]
Hello,

I am using The Events Calendar and The Events Calendar Category Colors plug-ins. I have checked the setting to show the Category Legend on the calendar, and I am seeing the legend when in the Month view, but not in the other views.
 
Should the legend also appear in the list and day views? The items have the color coding, but there is no legend to indicate what the colors mean.

Thanks,
Laura

**Comment by afragen** [comment]
Hey Laura!

Have you seen this page? https://github.com/afragen/the-events-calendar-category-colors/wiki/Adding-Legend-to-Additional-Views

I use a plugin to add extra settings. Feel free to fork it, https://github.com/afragen/category-colors-options

**Comment by FunWithWP** [comment]
Worked like a charm!
Thank you!
