### ISSUE TITLE
Clicking Category delivers nothing?

### ISSUE THREAD

**Issue by northwestresponse** [afragen/the-events-calendar-category-colors#101]
I have a category set up with "8" events in the calendar year.  However when it is clicked, I get _"No matching events listed under The Center For Wooden Boats. Please try viewing the full calendar for a complete list of events."_

What am I doing wrong?  
<img width="1344" alt="screen shot 2019-01-03 at 3 15 56 pm" src="https://user-images.githubusercontent.com/46360247/50666867-7af05980-0f6b-11e9-89cb-7db660e55554.png">
<img width="956" alt="screen shot 2019-01-03 at 3 19 38 pm" src="https://user-images.githubusercontent.com/46360247/50666873-7d52b380-0f6b-11e9-8f68-d2f19c1c0065.png">

**Comment by afragen** [comment]
You might need to be in a month with the event. If your current viewed month doesn’t have the event, that would be appropriate.

**Comment by northwestresponse** [comment]
Yea, I wasn't in a month with the event.  Darn.  Any chance this will be a feature in the future?

**Comment by afragen** [comment]
Honestly I’ll I’m doing is exposing the built-in category link. This would really be a feature request for Modern Tribe but I don’t think it’s likely. Sorry.

You might try the List view but this plugin doesn’t create those links.
