### ISSUE TITLE
Update for WordPress version 5.1

### ISSUE THREAD

**Issue by JoniWeiss** [afragen/the-events-calendar-category-colors#104]
Love the plugin! We're having some issues (reported to Modern Tribe) with The Events Calendar. This is the only plugin not tested for WP v5.1. 

Do you have a time-frame for releasing a version that's tested with WP 5.1?

Thanks!

**Comment by afragen** [comment]
It totally works with 5.1 and even 5.2 alpha. I simply haven’t updated the readme to reflect it.

**Comment by afragen** [comment]
What issues? Can you point me to where they are reported?

**Comment by JoniWeiss** [comment]
Sorry. the UI Errors are not at all indicating that this plugin has anything to do with it, and they only show up when submitting a new event. I only asked here as I noticed this plugin hadn't been updated for 5.1 and that concerns me.
