### ISSUE TITLE
Needs a "Reset Filter" link next to category colors

### ISSUE THREAD

**Issue by r-a-y** [afragen/the-events-calendar-category-colors#105]
Hi, we're using your plugin on our site and it's a great addition to The Events Calendar.

We think that a "Reset filter" link would be beneficial to users that do not know how to get back to the main calendar view after clicking on a category color.

Thanks for considering!  We're going to be implementing a temporary workaround in the meantime.

**Comment by afragen** [comment]
You should be able to use the `teccc_legend_html` filter to add a reset link.

https://github.com/afragen/the-events-calendar-category-colors/wiki/Filters-and-Hooks#teccc_legend_html

**Comment by r-a-y** [comment]
We already added one.  Thanks!
