### ISSUE TITLE
Suggestion: multiple colors in calendar view when multiple categories were chosen

### ISSUE THREAD

**Issue by wouterbruijning** [afragen/the-events-calendar-category-colors#106]
Hey guys, in our company we have five groups of people for whom we display events (mostly courses) on https://jaarplanning.kwadraad.nl/. We love the idea of the colors, so thanks for creating this! 

For convenience of our colleagues, we now create three instances of the same event so their color shows up. This is quite a hassle, and even more when an event consists of multiple meetings. 

If an event has multiple categories, the first category is chosen for the color. Would it be possible to add all colors of categories to the event in calendar view? Please see the first image for the idea (second column). 

I'm just an enthusiastic user, so I'm afraid I cannot help with coding... I hope this idea is possible. If not, thanks anyway for your plugin! 

Thanks,
Wouter 

<img width="988" alt="Screen Shot 2019-05-24 at 07 24 45" src="https://user-images.githubusercontent.com/4463665/58304551-0a03ee00-7df5-11e9-9709-a37dc02badc3.png">

<img width="1205" alt="Screen Shot 2019-05-24 at 07 00 53" src="https://user-images.githubusercontent.com/4463665/58304118-4d5d5d00-7df3-11e9-981a-410e4c809f29.png">

**Comment by afragen** [comment]
CSS doesn’t quite work this way. All the CSS targets the same selectors so the best you can do is have a border only category and a background only category and the 2 will show together.

**Comment by wouterbruijning** [comment]
Thanks for your time! Well, too bad. We'll manage one way or the other ;-)
