### ISSUE TITLE
Error on /the-events-calendar-category-colors/src/Category_Colors/Frontend.php

### ISSUE THREAD

**Issue by jykkemp** [afragen/the-events-calendar-category-colors#107]
Hi!

Our server provider app notified of two errors on Frontend.php:

"...PHP Warning:  Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' (this will throw an Error in a future version of PHP) in .../site/wp-content/plugins/the-events-calendar-category-colors/src/Category_Colors/Frontend.php on line 124
.../site/wp-content/plugins/the-events-calendar-category-colors/src/Category_Colors/Frontend.php on line 148..."

This caused my menu on "Appearance -> Menus" not showing, so I changed text in those lines from GLOB_BRACE to 'GLOB_BRACE' and it seems to work fine now.
Am not skilled in php (and am a noob to GitHub) so I just did what the app suggested :-)
And thought you should know.

Cheers.

**Comment by afragen** [comment]
https://wordpress.org/support/topic/error-messages-97/
