### ISSUE TITLE
Legend is showing all the categories

### ISSUE THREAD

**Issue by hidesignweb** [afragen/the-events-calendar-category-colors#109]
I have a main calendar that show all the event categories and the legend which is good. Then- I have separate month calendars for each category. and all the legends categories are showing. I only want the legend to show the 1 category for that particular month calendar since the only events showing are for that category  Thanks

**Comment by afragen** [comment]
You cannot only show particular categories in the legend on separate pages. Well, I guess you could, but you'd have to create a legend override. https://github.com/afragen/the-events-calendar-category-colors/wiki/Setting-up-template-overrides

If you don't want certain categories to show, use the `Hide` checkbox. It's the first checkbox in the Settings row for each category.
