### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Rouse-A** [afragen/the-events-calendar-category-colors#110]
I have been successfully using this app for some time.  However, I have just noticed that events on my website are no longer color-coded.

I'm using Version 6.3.2, together with The Events Calendar Version 4.9.11.  Has one of these been updated recently to cause the fault?

**Comment by afragen** [comment]
I believe TEC is an update. I’ve been working with them on their new views. 

Can you point to your calendar so I can see?

**Comment by Rouse-A** [comment]
Andy
After contacting you I continued to try to fix it. I re-checked the 
Settings and they correctly showed the configured colors. I then tried to 
modify one of the colors and updated the settings and it restored the 
correct working. I then changed the color back to the original and again 
updated the settings and it all worked as before.

It would seem therefore that the saved settings had become corrupted.


Regards
Alan Rouse
