### ISSUE TITLE
Legend Superpowers and mobile

### ISSUE THREAD

**Issue by afragen** [afragen/the-events-calendar-category-colors#111]
It really should work. Time to test.

**Comment by machouinard** [comment]
Hi, Andy.

What is the intended behavior on mobile?

I'm working with someone on his site and we've seen some different behavior on Month view.

- Superpowers always seem to work as expected on desktop.  
- At times we've seen superpowers work on mobile similar to how they do on desktop.  Tap a day and that day's events are listed beneath the calendar.  Tapping the legend highlights the associated events.  When this happens we're also unable to tap a different day in the month view.
- We've also seen the legend do nothing at all when tapped on mobile.  
- Currently on a [staging site](https://staging7.ranchermike.com/events/) we're seeing the legend on mobile link to the event category page while it works as expected on desktop.

He's using Avada and the only additional active plugin is Estatik, a real estate deal.

[Active plugins](https://i.imgur.com/53g72ZH.png)

Mark

**Comment by afragen** [comment]
Seems I needed to empty my browser cache 🤦‍♂️
