### ISSUE TITLE
Plans for "Updated Calendar Designs" support

### ISSUE THREAD

**Issue by squarecandy** [afragen/the-events-calendar-category-colors#112]
v5.x of The Events Calendar introduces an optional new "updated" set of theming. My first impression is that it is "slicker" looking out of the box, but much less useful for most people's needs.

Does this plugin plan to support those updated views too, eventually?

Does anyone have any info regarding if Tribe is going to support the old views indefinitely or if they will be retired at some point?

**Comment by afragen** [comment]
Absolutely, currently support is in the `shiny` branch but soon to merge into `develop`. It will be merged into `master` and on the dot org repo before that version of The Events Calendar is released.

**Comment by squarecandy** [comment]
Ah, cool - I'll check out the `shiny` branch.

FYI, Events Calendar and Events Calendar PRO 5.0.0 are both out today and while it doesn't automatically change the layout to the new one it does have some nags encouraging people to try it out - so it's out there in the wild now already. Not sure which version it defaults to on a fresh install, but existing projects definitely stay the same until you opt to upgrade.

**Comment by afragen** [comment]
Thanks. I didn’t realize it was released.
