### ISSUE TITLE
How to display the color on single-page views

### ISSUE THREAD

**Issue by TheWeeezel** [afragen/the-events-calendar-category-colors#113]
Hi, I'm searching for hours and can't figure this out. I have a single view in a custom theme and I would like the header and the background to be exactly the same colour as the category. But it seems the styles are not even loaded and also I can not access this colour category.

So I tried with teccc_fix_category_link_color but this is not giving me any results what so ever.

I have a styled single-page.php in my custom theme. And I would like to access the category colour.

Hope you can guide me towards a solution :D

**Comment by afragen** [comment]
If the view does not contain the `tribe_events_cat-{category-slug}` then the colors CSS have nothing to match.

**Comment by TheWeeezel** [comment]
Okay and how can i import it then? Im not sure i get it. :/

**Comment by afragen** [comment]
Is this a custom view?

You usually are missing the following in the 

v2 views `<article <?php tribe_classes( $classes ); ?>>`

legacy views `class="<?php tribe_events_event_classes() ?>" ` in the relevant location.

**Comment by TheWeeezel** [comment]
Sorry for my late reply. It is the Single-Event.php. So its definately the Legacy view. Because i now get it populated with the correct classes. But nonetheless the css is somehow not present i guess. 

`class="type-tribe_events post-15884 tribe-clearfix tribe-events-category-alle tribe-events-category-begegnungen tribe-events-venue-15428 tribe-events-organizer-15404 tribe-events-organizer-15840 tribe-events-organizer-15842 tribe-events-organizer-15844 tribe-events-organizer-15883 tribe-events-organizer-15853 tribe-events-first tribe-events-last"`

this is the classes which are loaded but they have no style.

**Comment by afragen** [comment]
Can you link to your calendar?

**Comment by TheWeeezel** [comment]
Unfortunately its a closed page. How can i contact you to give you the password

**Comment by TheWeeezel** [comment]
How can i add the created css to mi single-event page? As i understand it gets generated into the uploads folder
