### ISSUE TITLE
No longer working on other views

### ISSUE THREAD

**Issue by developerspal** [afragen/the-events-calendar-category-colors#114]
I have the following code in my child theme functions.php file

if ( class_exists( '\\Fragen\\Category_Colors\\Main' ) ) {
    teccc_add_legend_view( 'upcoming' );
	teccc_add_legend_view( 'photo' );
}

I have tried other views like day,week,upcoming but only month works which is the default view

Event calendar Pro Version 5.0.2

**Comment by afragen** [comment]
Take a look at https://github.com/afragen/the-events-calendar-category-colors/wiki/Adding-Legend-to-Additional-Views

`upcoming` hasn't been used by Modern Tribe for a while. You can take a look at https://github.com/afragen/category-colors-options for examples.

**Comment by developerspal** [comment]
you are rihgt but my issue the with 
teccc_add_legend_view( 'photo' );
it's not showing up there are the update to the new design which I did last night. No other customization in my child theme yet

**Comment by developerspal** [comment]
the only custom code in my functions.php is 
```
/*add legend color codes to calendar start*/

if ( class_exists( '\\Fragen\\Category_Colors\\Main' ) ) {

	teccc_add_legend_view( 'list' );
	teccc_add_legend_view( 'photo' );

}
/*add legend color codes to calendar end*/

/*add image guidelines start*/
add_action('tribe_events_community_section_before_featured_image', 'tribe_add_ce_image_notice');

function tribe_add_ce_image_notice() {
	echo '<p style="text-align: center;color:red;font-weight:bold;">Please submit an image that is 960px wide by 540px high</p>';
	

}

/*add legend via function call end */
```

**Comment by afragen** [comment]
My test site shows the same thing. I'll have to look and see if Modern Tribe changed the action hook.

https://tribe.thefragens.net/events/photo/

**Comment by developerspal** [comment]
Thanks for taking a look at this

**Comment by afragen** [comment]
I think this fixed it. https://github.com/afragen/the-events-calendar-category-colors/commit/2fcbcc08c56673eec298d31ca27b2faced6f1891

**Comment by developerspal** [comment]
Just an FYI it didn't work. I used the latest develop branch where you also fixed other views as well

**Comment by afragen** [comment]
Very odd as it's working on my test site above.

Can you try switching to a default theme to test?

**Comment by afragen** [comment]
It should be `teccc_add_legend_view('list');`, not _upcoming_.

**Comment by afragen** [comment]
BTW, my test site is running https://github.com/afragen/category-colors-options

**Comment by developerspal** [comment]
@afragen I just got it to work it seems that my settings were wiped that's why I couldn't see the legend bar. Works fine. Issue is resolved using develop branch. Thanks for taking the time. After looking at your profile I remembered that I "know" meaning I hear an interview you gave on the @wordfence postcast unless I am way way off base :)

**Comment by afragen** [comment]
Yep, that was me. 🙂
