### ISSUE TITLE
Event Category Colors Not Showing

### ISSUE THREAD

**Issue by CUTRKristin** [afragen/the-events-calendar-category-colors#115]
Hello - we just updated to the latest version of Word Press, and it seems the Event Category Colors are no longer working. Will you be updating the plug-in any time soon?

https://floridaltap.org/training-calendar/

**Comment by afragen** [comment]
You will likely need to update to the news events calendar views. The plugin has been updated to work with the current version of The Events Calendar.

**Comment by afragen** [comment]
I’m can’t seem to load the stylesheet for the plugin from your site.

**Comment by CUTRKristin** [comment]
Thanks - we haven't upgraded to the new calendar views, and I'm working to see if we can setup a staging site to do this. The link I sent just utilizes a shortcode, since we have Events Calendar Pro. Forgive me, as I am a bit of a novice in terms of web design...but happy to send you what you need to take a look - just let me know!

**Comment by afragen** [comment]
I just refreshed the CSS by adding the `refresh_css`query arg to the URL and everything looks correct now.

**Comment by CUTRKristin** [comment]
How can I replicate this? i'm still seeing the calendar without the category colors. This is what it looked like last week. 
![calendar](https://user-images.githubusercontent.com/64843757/84696399-711da480-af1a-11ea-815e-2e2a628eb379.png)

**Comment by afragen** [comment]
Add `?refresh_css` to the end of the calendar URL.
