### ISSUE TITLE
No change to colour!!

### ISSUE THREAD

**Issue by sofiabrown** [afragen/the-events-calendar-category-colors#116]
Amazing and powerful idea!! 

I followed the steps, updated in settings, however, no change is reflected.

I'm using Elemntor, with the following plugins

Livemesh Addons for Elementor
Premium Addons for Elementor
Essential Addons for Elementor

Please let me know if you can help?

many many thanks

--

**Comment by afragen** [comment]
If you could provide some screenshots of the Category Colors Settings and a URL for the calendar, I might be able to help.

**Comment by sofiabrown** [comment]
https://rr.dev.mywebmaster.co.uk/my-events/

![Screen Shot 2020-08-05 at 14 51 50](https://user-images.githubusercontent.com/24386548/89420902-46d2b100-d72b-11ea-8b45-9426a92f74bc.png)

it seems that Essential Addons for Elementor is overriding this plugin in as the colours set in Essential Addons for Elementor appear on the calendar vew

**Comment by afragen** [comment]
@sofiabrown unfortunately the site requires a login so I can't see what's conflicting.

I have several filters in place to possibly help fix these  sorts of issues.

**Comment by sofiabrown** [comment]
![Screen Shot 2020-08-23 at 23 46 19](https://user-images.githubusercontent.com/24386548/90990641-e2bd4300-e59a-11ea-84a5-1399f319eb42.png)

**Comment by afragen** [comment]
The above looks correct for mobile.

**Comment by sofiabrown** [comment]
oh. I thought that the plugin changes the colour of the Calendar items.. Perhaps I've misunderstood what the plugin was meant to do

![Screen Shot 2020-08-24 at 05 45 32](https://user-images.githubusercontent.com/24386548/91004809-1f099700-e5cd-11ea-8643-408d4742def5.png)

**Comment by sofiabrown** [comment]
It seems to work on the events page

![Screen Shot 2020-08-24 at 05 51 26](https://user-images.githubusercontent.com/24386548/91005105-ea4a0f80-e5cd-11ea-9eeb-2ba14b50415d.png)

**Comment by sofiabrown** [comment]
![Screen Shot 2020-08-24 at 05 53 36](https://user-images.githubusercontent.com/24386548/91005192-3301c880-e5ce-11ea-86f1-1f97f03fb25a.png)

**Comment by afragen** [comment]
The issue seems to be whatever you are using to create the embedded calendar in the `calendar-example` page is not using any of The Events Calendar's markup. Because of that it can't be styled with Category Colors.

**Comment by sofiabrown** [comment]
ok. Thank you. Its a great plugin!!! and you are very kind to spend time helping me understand -

I hope one day you can extend it to work with elementor.. so that I can create a number of events calendar with thie wonderful functionality

thank you once again

**Comment by afragen** [comment]
You are very welcome. Unfortunately it seems that inserting the calendar with Elementor strips away all of the usual Events Calendar classes.
