### ISSUE TITLE
Not working in List view after 12/03/2020 Update

### ISSUE THREAD

**Issue by tokazama2** [afragen/the-events-calendar-category-colors#119]
Today I updated to Events Calendar v5.3.0 and Pro 5.2.0. Now the category colors are not working in list view when using the tribe_events_list shortcode.  The colors DO work on the full calendar: https://ahforward.com/events/

https://ahforward.com/training/?refresh_css using tribe_events_list category="hcv" 

This is how it should look:
![category colors do work](https://user-images.githubusercontent.com/25513887/101054354-0bfc5080-3546-11eb-98f2-9b0a3579a5da.png)

This is how it looks after update:
![category colors don't work](https://user-images.githubusercontent.com/25513887/101054359-0d2d7d80-3546-11eb-894f-f3477363463e.png)

**Comment by afragen** [comment]
Thanks for the report. Can you try the `develop` branch and see if this is fixed?

To easily switch between branches you can install GitHub Updater, https://github.com/afragen/github-updater , and use the branch switching in the settings to switch branches from the plugins page.

**Comment by tokazama2** [comment]
I will give it a try tomorrow and let you know.

**Comment by tokazama2** [comment]
It works much better.  The css of the date to the left of the event details is still missing and the time is listed above the details and in a different format that I initially had it.  I suspect this is a problem with other functions in The Events Calendar.  If you have any ideas I am happy to have your guidance. Otherwise, thank you very much for getting the category colors working for me.
![category colors improvement made](https://user-images.githubusercontent.com/25513887/101192925-091e6000-3619-11eb-96c8-6e6a300a1606.png)

**Comment by afragen** [comment]
I'm sorry but Category Colors never did anything to the date. It only targets the title. I will release today. Thanks  for testing.
