### ISSUE TITLE
Widget event list: no colors after 12/03/2020 Update

### ISSUE THREAD

**Issue by RolandJosuran** [afragen/the-events-calendar-category-colors#120]
After the latest [update](https://theeventscalendar.com/release-notes/the-events-calendar/the-events-calendar-5-3-0/) of "The Events Calendar" (version 5.3), category colors were not shown in the events list in **widgets**. The events calendar's widget has a completely new design since version 5.3:

> The Events List widget has new templates and styles to complement the redesigned views released in The Events Calendar 5.0.

It seems, that css selectors need to be adapted. Is this just me (somehow related to my website or theme? Or does this also occure on other websites? 

Would be great, if you could update your awesome plugin, or give me a hint to fix this.

**Comment by afragen** [comment]
Are you using the latest version of the plugin? This was fixed a few days ago.

**Comment by RolandJosuran** [comment]
Thank you for your response. I have version 4.6.11 of TECC and 5.3 of TEC. The colors are there in the events list of the main part. But not on the widget in the sidebar. I'm using GeneratePress theme and has also testet twenty sixteen.

**Comment by afragen** [comment]
Can you share the URL? You likely need to refresh the CSS by adding the `?refresh_css` to the URL.

**Comment by RolandJosuran** [comment]
You are a genius! That solved the problem. Thank you very much. Please excuse my naive question. I am new to Wordpress and did not know this.
