### ISSUE TITLE
Mutliple categories - define colour from primary category

### ISSUE THREAD

**Issue by gs9824** [afragen/the-events-calendar-category-colors#121]
Hello, Thanks for the nice plugin ! 

I noticed that, when an event is in multiple categories, the colour is not taken from the primary category, but from the first category (in alphabetical order ?) 

Example : event is part of category 'group1' & 'group2' ('group2' is the primary category). The colour will be taken from 'group1' instead of the colour from the primary category ('group2')

**Comment by afragen** [comment]
That is correct. The categories are listed alphabetically in the CSS and the last defined CSS holds precedence. 

You can use a combination of border and background coloring. But those are really the only options.

You might search the forum for this plugin as this had come up before.
