### ISSUE TITLE
Legend in other views using Code Snippets

### ISSUE THREAD

**Issue by Jaybaz** [afragen/the-events-calendar-category-colors#122]
Hi,

I'm not incredibly 'tech' so bear with me. I hope you can help.

I'm trying to get the legend to appear above List, Day & Week views in addition to month. I've used the code provided in the Wiki and placed it in the Code Snippets plugin. It appears like the attached screenshot:
<img width="923" alt="Screenshot 2021-01-14 at 16 19 01" src="https://user-images.githubusercontent.com/77452172/104618194-4d733600-5684-11eb-8f01-d91efb2eb32f.png">

Once saved and activated, nothing appears to happen/change on the website.  Does this work with Code Snippets? I'm a bit nervous, given my lack of experience, about putting the code directly into the functions.php after hearing stories of sites crashing etc.

Any advice would be greatly appreciated.

Thanks

**Comment by afragen** [comment]
I have no idea how the code snippets plugin works. You can fork or modify https://github.com/afragen/category-colors-options and just modify some of the code there. It's what I use.
