### ISSUE TITLE
Are you supporting THC v5.0 

### ISSUE THREAD

**Issue by jvborne** [afragen/the-events-calendar-category-colors#125]
I see that in August the events calendar is requiring an update of the calendar display from the legacy version. Will you be supporting this version. I updated on one of my three sites using category color plugin and it did not appear to be working. I have come to rely on your good work to differentiate the events. Thank you.

**Comment by afragen** [comment]
Can you share a URL for what you're referring to? 

This plugin supports the current version of The Events Calendar and Events Calendar PRO.

**Comment by jvborne** [comment]
Thanks for getting back to me. The website in question is using just the free version and the Avada theme. The client has had very few events to post, so I’m, not sure if it is the best example. I posted one event to check how the new display version of the calendar would work, and found that it didn’t seem to take the color category assigned. That calendar is at: https://fcaemass.org/events/ <https://fcaemass.org/events/>

But the two other websites with THC that use the Pro version are heavily reliant on category colors. They are currently using the legacy calendar display. THC tells us that the legacy display will be discontinued in August. These two calendars are:

https://fmcquaker.org/calendar/ <https://fmcquaker.org/calendar/>

and

https://standrewswellesley.org/calendar/ <https://standrewswellesley.org/calendar/>

I also use the week view on the front pages of both of these websites. 

So, I am somewhat concerned about doing the “upgrade” out of the legacy display version. Am I going to have trouble here?

Thanks again for your really amazing and useful plugin.

Jonathan Vogel-Borne
ASA Graphics
7 Pleasant Place
Cambridge, MA 02139
617-599-8153
***@***.***

**Comment by afragen** [comment]
It is likely that your theme, Avada, is altering the default body classes causing the CSS selectors for the plugin to not work. You should be able to switch to a default theme to see that the plugin works correctly.

It will take some investigation on your part to determine what is causing this, but you can use some of the filter hooks to fix this. 

https://github.com/afragen/the-events-calendar-category-colors/wiki/Filters-and-Hooks#teccc_fix_category_link_color
https://github.com/afragen/the-events-calendar-category-colors/wiki/Filters-and-Hooks#teccc_fix_category_background_color
