### ISSUE TITLE
Selection Styling for Categories | Legend Superpowers

### ISSUE THREAD

**Issue by itsHall** [afragen/the-events-calendar-category-colors#127]
The selection and deselection styles on the categories in the legend are not working. They do work for the individual event articles in the calendar view, though. Is it more performant to apply the styles inline than it is to apply a class to the elements?

**Comment by afragen** [comment]
Can you paste an image of what you see the issue is?

**Comment by itsHall** [comment]
I expected the other categories to become transparent/fade like the non-selected events do in the calendar.

**Comment by afragen** [comment]
Can you share your calendar URL and also a link to the specific issue?

**Comment by itsHall** [comment]
https://www.marylandphysicianscare.com/wow-events/

When you select a category there is no easy way to tell which category is selected. 

On a side note (I understand if you can't answer this because its an issue with the main Events Calendar plugin): Do you happen to know why the URL is like this when switching months?: https://www.marylandphysicianscare.com/wow-events/(/?:month)/2021-06/

**Comment by afragen** [comment]
The way to tell what category is selected is that all events not in the selection are dimmed. Difficult to tell on the page with majority of events having grayish backgrounds.

**Comment by itsHall** [comment]
If the category you select doesn't have an event showing in the calendar view then everything just dims and the legend doesn't hint to the user which category is selected. Would it be possible to add the feature that the non-active categories in the legend are dimmed when there is an active one?

**Comment by afragen** [comment]
It's possible, but it's over my JavaScript abilities. I'm happy to receive PRs.

**Comment by ectu** [comment]
> Would it be possible to add the feature that the non-active categories in the legend are dimmed when there is an active one?

This is exactly what I need as well.
