### ISSUE TITLE
Category using Parent Event color not is own

### ISSUE THREAD

**Issue by wscit** [afragen/the-events-calendar-category-colors#135]
There seems to be an issue with the category color display which is affected by the naming of the 'sub category' and it's parent name.

Example of category hierarchy Dinghy is the parent and Adult Recreational sailing and Women on Water are sub categories (color of event):

Dinghy (Red)
-Adult Recreational Sailing (Blue)
-Women on Water (Green)

In the calendar  Adult Recreational Sailing shows Red not Blue.

- If I changed the name to **e**Adult Recreational Sailing it shows Blue as expected. 
- If I change the parent name to **a**Dinghy then Adult Recreational Sailing shows Blue as expected.
- If I prefix the sub category name 'Adult' with Di it shows Red but if use Dj it shows Blue. 

It looks like there is some alphabetic ordering effect causing the issue.

It's a really useful plugin. Thanks

**Comment by afragen** [comment]
CSS categories are created alphabetically. The only way to have 2 display is to combine a background as one and a border as another. 

Another solution is to use the checkbox to hide one of the categories from displaying any styling. 

To use your example. 

Digny - border red
  Adult Recreational Sailing background blue
  Women in Water - background green

**Comment by wscit** [comment]
Thank Andy
