### ISSUE TITLE
Category Colors CSS is not loading since most recent update

### ISSUE THREAD

**Issue by hjed** [afragen/the-events-calendar-category-colors#138]
Hi since the most recent update it looks like the plugin isn't actually sending the css to change the colours anymore (rest of the plugin is working just not the css)

**Comment by afragen** [comment]
Can you share your calendar URL?

**Comment by hjed** [comment]
Yep it's https://sydneynorthscouts.com/events/

**Comment by afragen** [comment]
You might try deactivating any plugin not relating to The Events Calendar and using a default theme. If the colors are back you must have a plugin or theme conflict. 

The CSS is being loaded.

**Comment by afragen** [comment]
I made a couple of changes, does the develop branch work for you? 

https://github.com/afragen/the-events-calendar-category-colors/archive/refs/heads/develop.zip

**Comment by hjed** [comment]
Brilliant, thanks. Yep that fixed it
