### ISSUE TITLE
Category colors no longer works on TEC 6.0.4 and TEC Pro 6.0.3 in list view

### ISSUE THREAD

**Issue by nhatvu208** [afragen/the-events-calendar-category-colors#140]
The list view does not show colours correctly, with some event names disappered

**Comment by afragen** [comment]
In my testing this works. 

Can you share you calendar URL?

**Comment by afragen** [comment]
I've heard of an issue with TEC 6.0.4 that was resolved with 6.0.5

**Comment by nhatvu208** [comment]
Sorry, I meant to say Summary view. Please look at the calendar here: https://events.platformcalgary.com/events/summary/?tribe-bar-date=2022-11-21

**Comment by afragen** [comment]
Hmm, seems to work on my test site, https://tribe.thefragens.net/events/summary/

Is this a special template on your site?

**Comment by nhatvu208** [comment]
Not that I know of. The site runs on Twenty Twenty Theme.

**Comment by afragen** [comment]
I'll take a closer look.

**Comment by afragen** [comment]
It now seems to be working.
