### ISSUE TITLE
Monthly calendar view freezes

### ISSUE THREAD

**Issue by Support71** [afragen/the-events-calendar-category-colors#141]
Since installing "the-events-calendar-category-colors" plugin, my calendar locks up and I can't view any events beyond February (screen shot attached). I would prefer to show the month calendar view and appreciate help getting that restored with the ability to move forward and backwards through the months. 

When I deactivate and then reactive your plugin the calendar view works for a few months before freezing up again. Hopefully you have a solution for this but in the meantime I will switch to list view for now. Here is the page for The Events Calendar on our website. https://aanorthdakota.org/events-and-news/ 

Thank you,

Randy Miller
![2023, 02, 26, 001](https://user-images.githubusercontent.com/126426767/221444000-9cfa27c7-d407-40f2-b37a-adfcc6555211.png)

**Comment by afragen** [comment]
You have a JS error in console when trying to switch views. Nothing to do with this plugin.

<img width="1055" alt="screenshot_306" src="https://user-images.githubusercontent.com/1296790/221645519-8370de09-22f1-4c49-a30e-22e18646350b.png">

You might  try The Events Calendar support forum.
