### ISSUE TITLE
Color priority on 2 categories

### ISSUE THREAD

**Issue by netinfoplc** [afragen/the-events-calendar-category-colors#142]
Hi,

I would like to ask the following please:

How can i set which color to be used when an event is assigned on 2 (or more) event categories?

Thank you in advance!

**Comment by afragen** [comment]
You can set one category to a border only and one to a background only. Both will display.

**Comment by netinfoplc** [comment]
Hi,

 

Sorry for getting back to this so late. 

 

Is there a way to set/choose the default background and border color in case the event is assigned in 2 categories?

 

Thanks again!
