### ISSUE TITLE
Legend Superpowers: we call `setup()` twice

### ISSUE THREAD

**Issue by barryhughes** [afragen/the-events-calendar-category-colors#146]
Unfortunately, I did just notice a (non-critical) issue following the merge of https://github.com/afragen/the-events-calendar-category-colors/pull/144 and https://github.com/afragen/the-events-calendar-category-colors/pull/145 that I somehow missed before now:

- Open month view, or other view where the legend superpowers are enabled.
- Click on a category (other categories should dim).
- Now reload the page.
- When the page reloads, those other categories should again be dimmed ... but this happens twice. Screencast (loops):

![double-setup-call](https://user-images.githubusercontent.com/3594411/227724589-f6a303fe-3024-4fe5-8386-c3457cc405d4.gif)

It seems like it is happening because, I think since [6.4.0](https://github.com/afragen/the-events-calendar-category-colors/blob/6.4.0/src/resources/legend-superpowers.js#L139), we've basically been calling the `setup()` function twice (for a while, three times):

- [Each page load](https://github.com/afragen/the-events-calendar-category-colors/blob/6.4.0/src/resources/legend-superpowers.js#L134)
- [After ajax loads](https://github.com/afragen/the-events-calendar-category-colors/blob/6.4.0/src/resources/legend-superpowers.js#L135) (since removed)
- [After the `afterSetup.tribeEvents` event](https://github.com/afragen/the-events-calendar-category-colors/blob/6.4.0/src/resources/legend-superpowers.js#L143)

It seems like `afterSetup.tribeEvents` will reliably fire on all versions of The Events Calendar from [5.0.0](https://github.com/the-events-calendar/the-events-calendar/blob/5.0.0/src/resources/js/views/manager.js#L154) (now 3yrs old) upwards ... that makes me think we could rely on that and remove our other call to `setup()`. Unless, of course, TECCC still needs to support earlier versions of TEC (and then we'd solve things differently).

Happy to submit a PR, but wanted to get your thoughts first (and also alert you to this).

**Comment by barryhughes** [comment]
...Apologies for not catching this at an earlier stage 😬

**Comment by afragen** [comment]
I'm more than happy to have TECCC not maintain backwards compatibility to less than the current version of TEC.

PR would be great.

**Comment by barryhughes** [comment]
Great—[PR submitted](https://github.com/afragen/the-events-calendar-category-colors/pull/147/)!

**Comment by afragen** [comment]
Thanks Barry!
