### ISSUE TITLE
Testing legend-superpowers

### ISSUE THREAD

**Issue by afragen** [afragen/the-events-calendar-category-colors#150]
@barryhughes on my test site, https://tribe.thefragens.net, I am having issues on mobile. Doesn't seem to be able to change view or select legend menu. 🧐

Almost as if JS not loading on mobile.

**Comment by barryhughes** [comment]
Something is definitely afoot, though I'm not sure what. On your site (check the exposed and weirdly spaced span tags):

![span-tags-funky-town](https://user-images.githubusercontent.com/3594411/229306656-c240c66e-0534-444d-b480-425832cf7bc0.png)

Yet locally I don't see the same when I drop into mobile view:

![legend-ok](https://user-images.githubusercontent.com/3594411/229306683-a22ced42-f673-4410-8f59-d3941f33ef93.png)

Will need to play and experiment a little 🕵🏼

**Comment by afragen** [comment]
I'm not seeing that either on laptop or iPhone.

**Comment by barryhughes** [comment]
OK, that's odd ... now I consistently see the `< span > ... < / span >` on all devices (when looking at tribe.thefragens.net, I mean) but I was sure when I last looked it was only on mobile.

**Comment by afragen** [comment]
I see it too now. Makes me wonder why WPCS for JS would do that. Let me fix it.

**Comment by afragen** [comment]
These are the "errors" phpcs is detecting.

```
137 | ERROR   | [x] Expected 1 space before "<"; 0 found (WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore)
 137 | ERROR   | [x] Expected 1 space after "<"; 0 found (WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter)
 137 | ERROR   | [x] Expected 1 space before ">"; 0 found (WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore)
 137 | ERROR   | [x] Expected 1 space after ">"; 0 found (WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter)
 137 | ERROR   | [x] Expected 1 space before "<"; 0 found (WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore)
 137 | ERROR   | [x] Expected 1 space after "<"; 0 found (WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter)
 137 | ERROR   | [x] Expected 1 space before "/"; 0 found (WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore)
 137 | ERROR   | [x] Expected 1 space after "/"; 0 found (WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter)
 137 | ERROR   | [x] Expected 1 space before ">"; 0 found (WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore)
 137 | ERROR   | [x] Expected 1 space after ">"; 0 found (WordPress.WhiteSpace.OperatorSpacing.NoSpaceAfter)
```

**Comment by afragen** [comment]
My guess is it has to do with being inside of backticks.

**Comment by barryhughes** [comment]
Yep, those rules probably make sense when applied outside of a string, in a comparison or when doing arithmetic. It would seem like a bug for them to be applied *inside* a string and outside of interpolated fragments.

That is, it might make sense to change:

```js
const myString = `<p>Hello ${ age<15 ? 'kid' : 'shipmate' }</p>`
```

Into:

```js
const myString = `<p>Hello ${ age < 15 ? 'kid' : 'shipmate' }</p>`
```

But not:

```js
const myString = ` < p > Hello ${ age < 15 ? 'kid' : 'shipmate' } < /p > `
```

**Comment by barryhughes** [comment]
Interesting: https://github.com/squizlabs/PHP_CodeSniffer/issues/2594.

Perhaps it is better to switch away to eslint or similar?

**Comment by afragen** [comment]
I updated `phpcs.xml` to not parse *.js

**Comment by barryhughes** [comment]
Let me know if you continue to see any odd behavior: I poked around and things are looking stable again when I test locally with the latest `develop` branch code.

(Though I do still see some weirdness on your test site, but I believe that is unrelated to these changes ... for instance, trying to switch to month view doesn't work, and I see the HTML response is `403 Forbidden`.)

**Comment by afragen** [comment]
Seems to be working in latest testing. I'll see about merging and release next week.
