### ISSUE TITLE
Add Filter or Hook for the filter bar

### ISSUE THREAD

**Issue by Cosirax** [afragen/the-events-calendar-category-colors#151]
Hey there,

thank you for this nice plugin. It would be very nice to have a hook or filter to choose the location of the filter bar related to the location hooks for tec. Like that I can choose wether the bar is above or beneeth the search bar.

Thank you in advance!

Greetings

**Comment by afragen** [comment]
That would be a hook in The Events Calendar not in this plugin.

**Comment by Cosirax** [comment]
okay, thank you for your reply. Could you tell me how I can achieve to change the location where the buttons are shown?
