### ISSUE TITLE
Settings in functions.php doesn't work. Help me please

### ISSUE THREAD

**Issue by AlexeyGonchar** [afragen/the-events-calendar-category-colors#57]
Hi there!

Would you help me, please!

I tried enclose all settings functions in the following code block to prevent any errors.

I added in functions.php:

if( class_exists( 'Tribe_Events_Category_Colors' )) {

teccc_add_legend_view( 'upcoming' );
teccc_add_legend_view( 'photo' );
teccc_add_legend_view( 'week' );
teccc_add_legend_view( 'day' );

teccc_ignore_slug('3d-kouching');

}

But it does not work ((( 
How to make it working well?

**Comment by afragen** [comment]
That looks like it should work. Can you point to a URL?

**Comment by AlexeyGonchar** [comment]
Hi, afragen! 

Thank you for attantion to my problem!

coach-portal.com/events - calendar on site

How it works - http://screencast.com/t/lNVN9UZ7kag

**Comment by afragen** [comment]
Your screencast was great. In your `functions.php` you have a closing `?>`, you have inserted the code after that. You should remove this closing tag as it's not required and is likely the source of your problem. Let me know.

**Comment by AlexeyGonchar** [comment]
Ok, clear! Thanks a lot!
