### ISSUE TITLE
Unable to create categories

### ISSUE THREAD

**Issue by happyaviator** [afragen/the-events-calendar-category-colors#60]
After adding the Category Colors plugin to my WP site I was unable to create new categories, from either within the Event Categories screen or when creating a new event.  Once I deactivate the plugin I am able to create categories.  Obviously something is broken here.

**Comment by afragen** [comment]
This is a new one. You should be able to create new categories from the Events > Event Categories. 

I was able to add a new Event Category t though on a mobile device the `Add New Event Category` did not reload the page but did add the category. 

Adding categories is not really a part of this plugin and I would recommend creating an issue on the ECP forum or the TEC forum.
