### ISSUE TITLE
Category Colors do not show when Printing

### ISSUE THREAD

**Issue by d4mation-** [afragen/the-events-calendar-category-colors#61]
I am not really sure why as you are using wp_enqueue_style() with the Media parameter set to its default ("all"), but nonetheless when in a Print Preview all the Categories show as gray. 

I've tried it on TwentyFifteen and the problem still existed so it shouldn't be a theme issue.

Although it is hard to see, the "June" link in the corner is still Green in the Print Preview.

<img src = "http://i.imgur.com/e5X6kMS.png" width = "400px">

**Comment by afragen** [comment]
Odd, it a quick local test for me using a simple child theme of twentyfourteen and latest versions of all plugins, I get colors, but any solid background colors are both absent. For some reason only the border color picks up.

![screenshot_01](https://cloud.githubusercontent.com/assets/1296790/8837455/82e3983c-3094-11e5-93da-169763b4ccbe.png)

![screenshot_03](https://cloud.githubusercontent.com/assets/1296790/8837590/ffe16f94-3094-11e5-923c-fe9d503fdde2.png)

You can see only the borders are showing.

I never really designed the plugin for printing but you might try adding a border color of the same color to the background and see how it prints.

There must be some override happening somewhere.

**Comment by d4mation-** [comment]
I just gave it another shot with all Plugins disabled (Besides The Events Calendar and this one) and I tried TwentyFourteen like you did and I had the same results as before. I've tested it in Chrome, Firefox, and Internet Explorer 11 and had the same results each time.

Yeah, most people don't really print these days, but it is something the client is interested in having. May have to resort to CSS like you said--I it would be nice if it were built-in so if the colors get changed for the categories the print styles would be updated too. No big deal though. I just wanted to bring this to your attention more than anything.

<img src = "http://i.imgur.com/7B5zTxz.png" width = "400px">

**Comment by afragen** [comment]
What I meant was to add the same color for the left border as for the background. That way at least the color will transfer even if it's just the border.

**Comment by d4mation-** [comment]
Ah, I misunderstood. Sorry about that.

Well, once I set the border color to match I was able to see the colors in the Print Preview window. Thank you so much for looking into this!

**Comment by afragen** [comment]
No problem. Please leave a review over on .org :+1:
