### ISSUE TITLE
accent

### ISSUE THREAD

**Issue by oniregoc** [afragen/the-events-calendar-category-colors#62]
Hello

In France we use accent like : à, é, è etc... when using a title like "balades à Paris" the category slug is "balades-a-paris" but it look like something is going wrong because in current display the title do not appear.

**Comment by afragen** [comment]
Can you share the URI for the calendar?

**Comment by oniregoc** [comment]
yes sure but the bug is really visible in the admin panel. Do you want me to open a limited user access to admin dashboard ? The web site is : http://www.lecolephoto.com

**Comment by oniregoc** [comment]
mmm...strange ! today it's working ! sorry about that. Thanks for your help.
