### ISSUE TITLE
using multiple categories

### ISSUE THREAD

**Issue by oniregoc** [afragen/the-events-calendar-category-colors#63]
hello,

when using categories with sub categories for one event only the first top is choosen as the color of the events which is not logical at all, exemple:
Balades
-Balades à Paris
--Balades à Montmartre

will use the color of the categorie "balades" for the event "balades à Montmartre" as "balades à paris"... but if we choose to make few different categories it of course to make a difference between them also with the colors. If all sub-categories get the top categories it's not logical.

Could you change this or add an option to let the user choose which way he like to use: top categorie or ending categorie ? Thanks for your great plugin !

**Comment by afragen** [comment]
There is an option to hide specific categories. It's the checkbox in the Settings page at the beginning of each category.

Does this not work?

**Comment by oniregoc** [comment]
well...I don't want to hide a categorie because I may use each of them. I just want that the last sub-categorie is use to display the right color not the first one...in the case of balades/balades à Paris/Balades à Montmartre only Balade à Montmartre should be used...for now it's "balades"

**Comment by afragen** [comment]
Unfortunately, CSS doesn't work that way. Only one style for a specific selector may be applied at a time and the last one declared is the one you see.

Perhaps a better solution would be to use certain categories only for organization and certain ones for display. Example, 'camera, for display and 'Nikon', 'Canon', etc for organization. In his example the 'camera' category would be colored and the model categories would be hidden.
