### ISSUE TITLE
Problem with WPML and events category colors

### ISSUE THREAD

**Issue by miguelcpz** [afragen/the-events-calendar-category-colors#64]
I have installed WPML - The events calendar and the events -calendar-category-colors. My events categories are translated in 3 languages. 
Colors for categories not shown in other languages. 
If you change the color settings  on other language it overwrite the english colors for categories and only shown the colors on the new language.

Could you help me with this problem, thanks in advance!!!

**Comment by afragen** [comment]
I'm not sure I'm capable of fixing this. The category class tag is based upon the category slug. If WPML is changing the slug then problems will arise.

Can you refer to the URL of the site?

**Comment by afragen** [comment]
May some of the following links will help.
https://wpml.org/forums/topic/categories-multiple-langs-same-slugs/#post-54232
http://wordpress.stackexchange.com/questions/135747/best-pratice-to-make-taxonomy-terms-translatable-without-changing-slugs
https://wpml.org/forums/topic/taxonomy-slugs-how-to-use-the-same-slug-for-two-taxs-in-two-different-langs/

**Comment by afragen** [comment]
I'm not sure it's that easy, but if it works -- great!

From Modern Tribe, https://theeventscalendar.com/knowledgebase/setting-up-the-events-calendar-with-wpml/

If you follow these directions and _don't translate_ the _Custom Taxonomies_, that might work.

**Comment by afragen** [comment]
I think I now have this fixed. See https://github.com/afragen/the-events-calendar-category-colors/wiki/Filters-and-Hooks#teccc_add_terms

**Comment by sperrenoud** [comment]
Not working.

Adding translation perfect !
As soon you validate color change in other language everything is lost, include base language...

Regards

**Comment by afragen** [comment]
@sperrenoud can you share the code you're using. Maybe I can test locally with it.

**Comment by kevinmckerracher** [comment]
I am having this issue still with Categorie colours and WPML. I can't set the colours for the French side. I have tried the hook code in functions file and it did nothing.
