### ISSUE TITLE
CSS Path issue when wordpress is in subfolder

### ISSUE THREAD

**Issue by IndigoStarfish** [afragen/the-events-calendar-category-colors#65]
https://github.com/afragen/the-events-calendar-category-colors/blob/develop/src/Category_Colors/Frontend.php#L52

Change home_url to home_url('/') to stop generating http://example.org/test?teccc_css=... urls and instead generate http://example.org/test/?teccc_css=... urls.

**Comment by afragen** [comment]
I will test this. Thanks.

**Comment by afragen** [comment]
Thanks. Fixed in next release. https://github.com/afragen/the-events-calendar-category-colors/commit/7bad9527ce597fc52d281b0f538423c27dc0da0c
