### ISSUE TITLE
Category colors text being overwritten after update

### ISSUE THREAD

**Issue by jenmenke** [afragen/the-events-calendar-category-colors#67]
warning: I am not super good at this stuff so replies need to be fairly basic. 

url: http://www.mayerlutheran.org/events/

After latest plugin update, the text on all my events, no matter what the category color is set to has changed to #d31245 (red).

Not sure how to fix this.

**Comment by afragen** [comment]
@jenmenke the plugin's  CSS is being overridden by your theme's CSS
http://www.mayerlutheran.org/wp-content/themes/mayer/css/styles.css on line 84

The reason is that your theme adds a div id of 'homeContent' thereby changing the usual CSS selector structure.

If you comment out that line in your theme's style.css you won't have red links on your site, but the colors will work.

**Comment by jenmenke** [comment]
I literally hate how this site is set up. It's so foreign to me that I have trouble making the most mundane fixes. I was going to do just what you suggest, but after inspecting the site further, I saw that 'homeContent' is literally everywhere. If I comment it out I will lose the red font where I actually do want it. So I was unsure how to get Events Category Color to override the div id. Can I even do that?

**Comment by afragen** [comment]
Unfortunately, I you can't get Category Colors to override that without making changes to the plugin.

You'll likely have to switch themes to remove that id tag, but that's going a bit overboard. Sorry, I don't think there's an easy solution.

The other way to do it is to have your theme designer rewrite a bunch of the theme to not use that added id selector, 'homeContent'.

**Comment by afragen** [comment]
@jenmenke can you try the `inline-css-option` branch and see if that fixes it for you?

**Comment by jenmenke** [comment]
doing it now. give me a few minutes to log in and figure it all out.


On Feb 15, 2016, at 11:01 AM, Andy Fragen <notifications@github.com> wrote:

@jenmenke <https://github.com/jenmenke> can you try the inline-css-option branch and see if that fixes it for you?

**Comment by afragen** [comment]
If that doesn't work I may have to add a few filters to add those selectors that need overriding in the theme's CSS.

**Comment by jenmenke** [comment]
I assumed I was going to be changing css on the theme or inside the plug-in. Are you wanting me instead to update the plug-in with the one you posted on github?


On Feb 15, 2016, at 11:12 AM, Andy Fragen <notifications@github.com> wrote:

If that doesn't work I may have to add a few filters to add those selectors that need overriding in the theme's CSS.

**Comment by afragen** [comment]
I'm not sure the new idea/branch will work for you, perhaps I'll need to look at something a bit different. I'll have to see if I can reproduce this issue by altering my own CSS to colorize that tag. 

Stay tuned.

**Comment by jenmenke** [comment]
I’m supposed to install it as a new plugin and deactivate the current Category Colors, though, correct?

This Wordpress theme… My hands are tied. It’s so frustrating. It was custom written for the school and I HATE IT because it is SO unconventional. I can seem to troubleshoot anything. :(


On Feb 15, 2016, at 11:25 AM, Andy Fragen <notifications@github.com> wrote:

I'm not sure the new idea/branch will work for you, perhaps I'll need to look at something a bit different. I'll have to see if I can reproduce this issue by altering my own CSS to colorize that tag.

Stay tuned.

**Comment by afragen** [comment]
Yes, deactivate original and install and activate this branch. In Settings check "Use Inline CSS"

**Comment by jenmenke** [comment]
bah. it didn’t work.

Then I deactivated the new one to see what the calendar would look like and it’s all red (link) type. I don’t understand why it changed. Did something change in the update from a few weeks ago? I know for sure that I didn’t change the theme at all.

http://www.mayerlutheran.org/events/

anyway. very much appreciate the help. Sorry to be a pain
Jennie

On Feb 15, 2016, at 11:29 AM, Andy Fragen <notifications@github.com> wrote:

Yes, deactivate original and install and activate this branch. In Settings check "Use Inline CSS"

**Comment by afragen** [comment]
Did you check the new setting? I'm don't see the CSS added.

**Comment by jenmenke** [comment]
sorry. I’ll put it back. I deactivated the plugin to see what happened. I reactivated it and checked “use inline css”

http://www.mayerlutheran.org/events/

On Feb 15, 2016, at 11:45 AM, Andy Fragen <notifications@github.com> wrote:

Did you check the new setting? I'm don't see the CSS added.

**Comment by afragen** [comment]
The new branch doesn't work. I was able to recreate your problem.

I was also able to create a solution, now I just need to figure out how to code it.

**Comment by afragen** [comment]
Try the branch `filter-link-color`. Then add the following to your theme's functions.php

```php
add_filter( 'teccc_fix_category_link_color', function() {
	return '#homeContent';
});
```

Let me know how it works.

**Comment by jenmenke** [comment]
what do you mean when you say “try the branch” filter-link-color?

I’ve added the code to functions.php


On Feb 15, 2016, at 1:58 PM, Andy Fragen <notifications@github.com> wrote:

Try the branch filter-link-color. Then add the following to your theme's functions.php

add_filter( 'teccc_fix_category_link_color', function() {
    return '#homeContent';
});
Let me know how it works.

**Comment by afragen** [comment]
Download and install, https://github.com/afragen/the-events-calendar-category-colors/archive/filter-link-color.zip

**Comment by jenmenke** [comment]
that appears to have worked! I’m trying to tweak some of the category colors. te a look

http://www.mayerlutheran.org/events/month/


On Feb 15, 2016, at 2:13 PM, Andy Fragen <notifications@github.com> wrote:

Download and install, https://github.com/afragen/the-events-calendar-category-colors/archive/filter-link-color.zip <https://github.com/afragen/the-events-calendar-category-colors/archive/filter-link-color.zip>

**Comment by afragen** [comment]
Go Crusaders!

**Comment by jenmenke** [comment]
Ha! thanks so MUCH for all your help!

On Feb 15, 2016, at 2:38 PM, Andy Fragen <notifications@github.com> wrote:

Go Crusaders!

**Comment by afragen** [comment]
You're welcome Jen. You can keep using the plugin you're using and switch when the Category Colors v4.5.0 comes out.

**Comment by jenmenke** [comment]
Will do. thanks again and have a great week

On Feb 15, 2016, at 2:48 PM, Andy Fragen <notifications@github.com> wrote:

You're welcome Jen. You can keep using the plugin you're using and switch when the Category Colors v4.5.0 comes out.
