### ISSUE TITLE
The Events Calendar Category Colors  Colors not displaying

### ISSUE THREAD

**Issue by peconca** [afragen/the-events-calendar-category-colors#68]
Hi
Am running PHP version: 5.4.26, WordPress 4.1.10 running Altair theme, The Events Calendar Version 4.0.5, and The Events Calendar Category Colors Version 4.4.5.  I have checked all the settings and documentation. URL is http://prince-edward-county.com/events-test/
I have tried de-activating all the plugins, but to no avail.
I know that the FTCalendar plugin is not compatible with The Events Calendar, but even when it is deactivated the Category colors do not work. Do you know if the Altair theme is not compatible with this plugin?

**Comment by afragen** [comment]
If you have a staging server I would suggest you start by deactivating all plugins not related to the Events Calendar and see if it works. Alternatively you could try switching to a default theme and see if it works.

I am not familiar with the Altair theme.

**Comment by afragen** [comment]
I'm closing this as it seems you are no longer using this plugin.
