### ISSUE TITLE
Category colors don't like accent

### ISSUE THREAD

**Issue by oniregoc** [afragen/the-events-calendar-category-colors#69]
Hello,

in settings when your categorie title (not the slug...the title) is like "Balade à Paris" the title in settings do not appear because of the accent on the "a". It does work fine with "é" or "è" and that make the color desapear completly on front end when you try any update !

**Comment by afragen** [comment]
Can you provide a screenshot so I can see it?

**Comment by oniregoc** [comment]
Sure !
![2016-04-06_095331](https://cloud.githubusercontent.com/assets/11138014/14309661/3d22ed1e-fbde-11e5-9995-fcad4fee661d.jpg)

![2016-04-06_095525](https://cloud.githubusercontent.com/assets/11138014/14309667/439c491a-fbde-11e5-87d0-04738f8937fc.jpg)

and the front end is without any color if you have only one "à"

**Comment by afragen** [comment]
Can you deactivate Category Colors and then try to recreate this issue. I think this might be in the main plugin as Category Colors only reads the categories it doesn't set them.

**Comment by afragen** [comment]
I noticed that this same issue was #62 but that stopped. Has something else changed?

**Comment by oniregoc** [comment]
I don't know because I finally use a workaround: I don't use anymore "à" in categorie...and I am just too busy to test it. But thanks for your support !

**Comment by afragen** [comment]
Sorry, if you ever want to continue troubleshooting let me know.
