### ISSUE TITLE
filter categories 

### ISSUE THREAD

**Issue by robbvann13** [afragen/the-events-calendar-category-colors#74]
When I click on a month and than select a category it reverts back to the current month instead of staying on the selected month. Any idea on how to fix it, I am new to PHP and would appreciate any advice you have. 

Thanks and great plugin BTW!

**Comment by afragen** [comment]
I believe this is a function of TEC and not the Category Colors plugin. The only _navigation_ I do is using _legend superpowers_ or a built-in link to the category. How WP handles links from there isn't part of the plugin.
