### ISSUE TITLE
After installation of PlugIn update 4.6.3 the category colors are not more available

### ISSUE THREAD

**Issue by UschiB** [afragen/the-events-calendar-category-colors#77]
Hello
I installed the new Plugin 4.6.3 and now the categories colors are not more available in the calendar and also the tab in the events calendar to configure the colors disapeared.
I have events calendar 4.4.2, WordPress 4.7.2. and php 5.5

**Comment by afragen** [comment]
I'm running all these same versions on several of my test sites and it's all present on my end.

The early return I added was if the class `Tribe__Events__Main` does not exist. That is the main class for The Events Calendar.

Can you share your site's URL?

**Comment by UschiB** [comment]
Hi

my sites URL is www.golfclub-rickenbach.de <http://www.golfclub-rickenbach.de/>

Best Regards
Ursula

Ursula Bühler 
Interaction Designer - Requirements Engineer
Informatiker  - Web Publisher SIZ

web publishing
Frankenstr. 8
CH-4313 Möhlin 
Phone +41 61 851 04 04 
Mobile +41 79 173 48 26

**Comment by afragen** [comment]
Can you make sure that the Category Colors plugin is active?

**Comment by UschiB** [comment]
Hi

yes it is active (see screen shot)

I removed it once and installed it again, but still the same.

Kind Regards
Ursula


Ursula Bühler 
Interaction Designer - Requirements Engineer
Informatiker  - Web Publisher SIZ

web publishing
Frankenstr. 8
CH-4313 Möhlin 
Phone +41 61 851 04 04 
Mobile +41 79 173 48 26

**Comment by afragen** [comment]
I just pushed an update to move the graceful exit just before the category colors activation. I think you may have gotten caught where the Category Colors plugin was loading before the Events Calendar plugin.

Let me know if v4.6.4 fixes it.

BTW, the screenshot doesn't have a link.

**Comment by UschiB** [comment]
Hi Andy

this works, thank you!
I just have to redefine all colors.

Nice evening,
Kind regards
Ursula

Ursula Bühler 
Interaction Designer - Requirements Engineer
Informatiker  - Web Publisher SIZ

web publishing
Frankenstr. 8
CH-4313 Möhlin 
Phone +41 61 851 04 04 
Mobile +41 79 173 48 26

**Comment by afragen** [comment]
Excellent! Thanks for pointing out the issue for me.
