### ISSUE TITLE
Category Colours not rendering

### ISSUE THREAD

**Issue by ljknechtel** [afragen/the-events-calendar-category-colors#78]
Installed plugin, but not able to see/customize colors. This is what I see: http://take.ms/bptry

Using latest version of WP (4.7.3)
Please assist.

**Comment by afragen** [comment]
Do you have any Event Categories created?

**Comment by ljknechtel** [comment]
Oh you are a smarty, @afragen. ;)
Thanks so much. Have a wonderful day.

**Comment by afragen** [comment]
This isn't the first time and the image made it possible to identify. 😁
