### ISSUE TITLE
Stopped working with WordPress 4.7.5?

### ISSUE THREAD

**Issue by skuske** [afragen/the-events-calendar-category-colors#80]
After updating WordPress to v4.7.5 the plugin seems to have stopped working. Can someone confirm that? Reinstalling the plugin does not help. It appears in the list of installed plugins, but that's it...

The Category Colors tab is also gone...

TIA,

Stefan

**Comment by afragen** [comment]
It's all working here. Both on 4.7.5 and latest 4.8 beta.

Is the plugin activated?

**Comment by skuske** [comment]
Yes, activated, and showing up in the list of active plugins, but no category colors tab, and the colors themselves disappeared, too...

**Comment by afragen** [comment]
Can you screenshot the plugins page and the Settings page. Also the calendar URL would help.

**Comment by skuske** [comment]
See below. It partly came back, bot only a dark blue line is displayed next to an event:

http://knabengesang.de/events/

However, still no category colors tab and no way to configure anything. The plugin is activated.

![bildschirmfoto 2017-05-17 um 19 11 37](https://cloud.githubusercontent.com/assets/12996815/26166761/e9ccd14c-3b34-11e7-9c09-195179537108.png)

**Comment by skuske** [comment]
It's back. Sorry for the trouble. :)

**Comment by afragen** [comment]
No problem. Glad it's all working.
