### ISSUE TITLE
Legend on list view?

### ISSUE THREAD

**Issue by skuske** [afragen/the-events-calendar-category-colors#81]
I cannot find a way to add the legend to the list view... Am I missing something? Thanks! :)

**Comment by afragen** [comment]
Yes, you're missing the wiki. 😢 
https://github.com/afragen/the-events-calendar-category-colors/wiki/Adding-Legend-to-Additional-Views

Remember to look at this too. https://github.com/afragen/the-events-calendar-category-colors/wiki/Customizing-Category-Colors-Plugin
