### ISSUE TITLE
Request to support 'Event Calendar Templates' plugin

### ISSUE THREAD

**Issue by skuske** [afragen/the-events-calendar-category-colors#82]
It would be so cool if 

https://de.wordpress.org/plugins/template-events-calendar/

would be supported, too.  Especially the timeline views of that plugin as they are really great, but would really need some category coloring... :)

Thanks! :)

**Comment by afragen** [comment]
If the events categories are part of that plugin's output en it might be possible, but it looks like they already have styling.
