### ISSUE TITLE
Multiple categories?

### ISSUE THREAD

**Issue by ENeMy235** [afragen/the-events-calendar-category-colors#84]
Hello. I have events with multiple categories. Is it possible to show all colors for one event? For example Event 1 has 3 categories (1 blue, 2 red, 3 green). And I need to show all these 3 border colors in widget side by side.

**Comment by afragen** [comment]
It’s not possible as that’s not the way CSS works. I suggest using the hide category feature in Settings and try to focus on one of the categories. That way you still get the benefit of searching for specific categories.
