### ISSUE TITLE
Add category events colors to calendars build using shortcodes

### ISSUE THREAD

**Issue by abhishekjain16** [afragen/the-events-calendar-category-colors#85]
Hi,

Is there a way we can enable colors when event calendar is built using shortcodes like [tribe_events] ?

I was able to add colors to the main event, but I have a second calendar on another page which is built using shortcode [tribe_events] and it is not reflecting the colors in it's category. Please help!

Thanks a lot

**Comment by afragen** [comment]
This was added in January 2016. https://github.com/afragen/the-events-calendar-category-colors/commit/d818581b943b6f286e00aca3fb313c4a54b373b8#diff-17a0cd1d836b24ca98e2634c4956ced1
