### ISSUE TITLE
Keep Getting Error - The Events Calendar Category Colors cannot run on PHP versions older than 5.3.0. 

### ISSUE THREAD

**Issue by LaneLee1** [afragen/the-events-calendar-category-colors#86]
It was working fine then all the sudden I get this "The Events Calendar Category Colors cannot run on PHP versions older than 5.3.0. Please contact your hosting provider to update your site."  I contacted bluehost and we upgraded specifically to 5.6.0 PHP ..  Deleted the plugin added again etc.  Keeps giving me this error?  Any ideas??

**Comment by afragen** [comment]
You will need to contact Bluehost again as that particular site must not yet be on PHP 5.6.

**Comment by LaneLee1** [comment]
Thanks Got it working now!

**Comment by afragen** [comment]
Great!
