### ISSUE TITLE
Is possible to used with list mode ?

### ISSUE THREAD

**Issue by Shiva30** [afragen/the-events-calendar-category-colors#88]
Hello,

i try it, it's really fantastic on month view. I would like to use in list mode (by day). But nothing display ? I miss something, it's normal ? 

Thanks for your help.

**Comment by afragen** [comment]
Take a look at the wiki. https://github.com/afragen/the-events-calendar-category-colors/wiki/Adding-Legend-to-Additional-Views

**Comment by Shiva30** [comment]
Thanks a lot, i have not read this. All work ;)
