### ISSUE TITLE
Superpowers Not Doing Anything in Photo View

### ISSUE THREAD

**Issue by jonahcoyote** [afragen/the-events-calendar-category-colors#89]
Hey guys! 

Thanks for the great plugin and hope all is well. 

I'm trying to implement superpowers on photo view and I'm not seeing anything happen. The legend shows fine, and looking at the HTML I'm not seeing anything happen when clicking on any of my categories. There's no js errors in the console and nothing else looks off so I'm a bit perplexed. It should have the same effect where the opacity is modified correct?

**Comment by afragen** [comment]
Superpowers only works in the month view. But I’m happy to have a PR.

**Comment by afragen** [comment]
Hey Jonah! BTW, you do realize this plugin was based on your, now 404, knowledge base article.

**Comment by afragen** [comment]
This is now working with the latest version of the plugin and TECs new views.
