### ISSUE TITLE
Colors missing in IE 11 - reduced view does not display a visual item.

### ISSUE THREAD

**Issue by coralcuts** [afragen/the-events-calendar-category-colors#91]
Hello,
Using Calendar in month view. In firefox, category text and colors display. In IE, the colors don't display, the text does though. A larger problem occurs when the calendar is reduced in size, so items only get an symbol\icon and no text to represent a calendar item. In firefox, just the colors display which is good, but in IE, nothing is displayed. The category colors addition appears to remove the default icon to show that something is on a month calendar day. A user can click on a day, and the items display below the calendar view. However, users don't have a visual of the days that have items.

**Comment by afragen** [comment]
Can you give the URL of the calendar?

**Comment by coralcuts** [comment]
http://www.lifelinecpr.com/wordpress/calendar

**Comment by afragen** [comment]
I’ll take a look when I get near a Windows machine next week.

**Comment by afragen** [comment]
To be clear the issue seems to be that in IE11 the mobile view is not showing. Category Colors does remove the daily indicator in mobile view in favor of the color bars.

**Comment by coralcuts** [comment]
Resolved this with the following change:
.\views\category.css.php
line 64
Description: Add space between 'solid' and color attribute
Original: ...border-left: 5px solid<?php esc_attr_e( $options[ $slug . '-border' ] ) ?>
Change: ...border-left: 5px solid <?php esc_attr_e( $options[ $slug . '-border' ] ) ?>
Notes: Clear server, client caches & use ?refresh_css on url.

**Comment by afragen** [comment]
@coralcuts did you want to submit a PR? Otherwise I’ll be happy to fix it and thanks for finding it. Obviously my mistake.

**Comment by coralcuts** [comment]
@afragen - would appreciate it if you can submit the code change. Thanks for your efforts on the plugin!

**Comment by afragen** [comment]
Will do. And thanks for finding the bug for me.
