### ISSUE TITLE
WEEK view features needed!! 

### ISSUE THREAD

**Issue by kgotzenberg** [afragen/the-events-calendar-category-colors#92]
I just downloaded Category Color setting. Love the colored calendar.
We have a simple 3-day event in our community that has a lot of individual events happening over three days. How can I make this product do the following:
-Show ONLY the three days of the event (in the WEEK MODE VIEW) -- August 23-35, 2018
-Show ONLY the time of day that my events are active (i.e. day starting at 8:00 am, ending at midnight)
-Have the Legend & Legend Superpowers work in the WEEK MODE VIEW (My guests want to filter on the category of events they are interested in
-I would love to have the finished WEEK MODE VIEW calendar exportable as a PDF, so we can publish it in our Souvenir Program

You help would be very appreciated

**Comment by afragen** [comment]
That’s quite a list. I’m not sure I can help with much of it as the week view and it’s display is core to the Events Calendar PRO plugin. I don’t think I can change that.

The legend can display in the week view. Take a look at the wiki. However, legend superpowers only work in the month view. If you can get it to work in any other views a PR would be appreciated. Thanks and I’m glad you like the Category Colors plugin.
