### ISSUE TITLE
Colors not showing on month view hover

### ISSUE THREAD

**Issue by jvborne** [afragen/the-events-calendar-category-colors#94]
I have two sites using the calendar category colors. I just updated one of the sites with the current The Events Calendar (v4.6.19) and TEC Pro (4.4.28) and find that the color category with the knockout white type no longer appears when you hover over an event in month view. 

![image](https://user-images.githubusercontent.com/5993450/42221471-1a4ae3fe-7ea0-11e8-95ed-4d5a13603155.png)

Whereas in the site I have yet to update using the prior versions of TEC and TEC Pro, the event title with the knockout white type with the color category appears:

![image](https://user-images.githubusercontent.com/5993450/42221550-651a9e56-7ea0-11e8-944e-a90456d453b4.png)

Any suggestions? Comments?

**Comment by jvborne** [comment]
Here are the URLs for the two website calendars:

The one without the color category being applied, using the current versions of TEC/Pro

https://fmcquaker.org/calendar/

And the one where the color categories are being applied "correctly", using a prior version of TEC/Pro:

https://standrewswellesley.org/calendar/

================

One thing I have noticed in when inspecting the code is that the "problem" calendar uses an h3 for the title and the "correct" calendar is using an h4. The theme is Avada and for all intents and purposes, I had assumed these installs were the same, if not identical in their settings.

What is up?

**Comment by afragen** [comment]
I actually fixed this in the `develop` branch yesterday. It’s not Avada. I think the TEC changed the tooltip from h4 to h3. https://github.com/afragen/the-events-calendar-category-colors/commit/8815e682ea1810cfd8a3834d69694b5397bd3483

I should be merging into the master and releasing next week. I’m leaving town for a few starting today.

Thanks for the report.

**Comment by afragen** [comment]
FYI https://github.com/moderntribe/the-events-calendar/commit/4d1a13ae1a842a6ac844659e1e50f2e446cd97a4#diff-77360f51e8432159c352f87727f7ae39

**Comment by jvborne** [comment]
Thank you. I look forward to the update.

**Comment by jvborne** [comment]
Any news on a new release that changes the tooltip head as per your email below?? 

Thank you for good work!

Jonathan Vogel-Borne
ASA Graphics
7 Pleasant Place
Cambridge, MA 02139
617-599-8153
jvb@thebornes.org
Skype: jvborne

**Comment by afragen** [comment]
Should be later today.
