### ISSUE TITLE
Color on tribe week shortcode widget not showing

### ISSUE THREAD

**Issue by jvborne** [afragen/the-events-calendar-category-colors#95]
Using the tribe shortcode [tribe_this_week count="5"] on my front page, with the most recent update, 5.2.2., the background colors on my front page weekly calendar widget disappeared (see image below).

![image](https://user-images.githubusercontent.com/5993450/43399762-e0a8a20e-93d9-11e8-9b96-ff178f324f6d.png)

Reverting to 5.1.0 the colors returned…

![image](https://user-images.githubusercontent.com/5993450/43399917-470aa592-93da-11e8-9678-c0c641c1dc79.png)

Thanks for your help and your amazing work!

**Comment by afragen** [comment]
I was _fixing_ some stuff. I guess I went too far. 😞

**Comment by afragen** [comment]
Can you take a look at the `develop` branch. It seems to be working for me.

**Comment by afragen** [comment]
Does this work with v5.3.0?

**Comment by jvborne** [comment]
Thanks for checking in Andy. I am out of town until Thursday and can look at this then. 

Jonathan

**Comment by afragen** [comment]
@jvborne is this still not working for you?

**Comment by jvborne** [comment]
Yes it is. Thank you so much!! I appreciate your due diligence.

Jonathan Vogel-Borne
ASA Graphics
7 Pleasant Place
Cambridge, MA 02139
617-599-8153
jvb@thebornes.org
Skype: jvborne

**Comment by afragen** [comment]
So working or not working?

**Comment by afragen** [comment]
And are you on latest version?

**Comment by jvborne** [comment]
Yes it is working. I am on version 6.0


Here is the week view on two different widgets. Horizontal and Vertical






Jonathan

**Comment by jvborne** [comment]
Closed the issue. Sorry to have left it open on GitHub.

Jonathan
