### ISSUE TITLE
 Category Colors and format removed when updated plugin

### ISSUE THREAD

**Issue by ndmarkley** [afragen/the-events-calendar-category-colors#96]
So, I just updated the events calendar plugin to the current version Version: 4.6.21
Author: Modern Tribe, Inc. 
and I updated your plugin to the current version. 
Now the categories colors and format is removed (see screen shot) 
Looks like the events calendar plugin caused this updated updated cause I updated yours first and was fine. But, wanted to let you know in case you have to do something on your end. 
![color](https://user-images.githubusercontent.com/7587056/43600466-a23d7e8c-9658-11e8-9009-871be0974f94.PNG)

**Comment by afragen** [comment]
Can you share the URL to your events page?

What version of Category Colors are you using?

**Comment by afragen** [comment]
Is WordPress installed in a subdirectory? If so, try the develop branch.

**Comment by ndmarkley** [comment]
That worked. 
I downloaded the develop branch and installed and it fixed the problem. Thanks for the help. 

![ecc2](https://user-images.githubusercontent.com/7587056/43608290-c8661e96-966e-11e8-8fc6-0ac14b45dccc.PNG)
